// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeCHUtyhulrepz5gNmJctXHITISEtI4Zg',
    appId: '1:181662988899:web:5bc45f3e9ed5406dab1656',
    messagingSenderId: '181662988899',
    projectId: 'wisdom-class-management',
    authDomain: 'wisdom-class-management.firebaseapp.com',
    storageBucket: 'wisdom-class-management.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd4zxjIZEW6NSJC1U8rj65BxjN9AHqL_A',
    appId: '1:181662988899:android:119a9abea6cb6060ab1656',
    messagingSenderId: '181662988899',
    projectId: 'wisdom-class-management',
    storageBucket: 'wisdom-class-management.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC032Z0Ox2B3leP-9sSgE-0DZSQZE-pDvo',
    appId: '1:181662988899:ios:6dc81248012df4b3ab1656',
    messagingSenderId: '181662988899',
    projectId: 'wisdom-class-management',
    storageBucket: 'wisdom-class-management.firebasestorage.app',
    iosBundleId: 'com.example.wisdomClassManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC032Z0Ox2B3leP-9sSgE-0DZSQZE-pDvo',
    appId: '1:181662988899:ios:6dc81248012df4b3ab1656',
    messagingSenderId: '181662988899',
    projectId: 'wisdom-class-management',
    storageBucket: 'wisdom-class-management.firebasestorage.app',
    iosBundleId: 'com.example.wisdomClassManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeCHUtyhulrepz5gNmJctXHITISEtI4Zg',
    appId: '1:181662988899:web:4d7f911908e81e74ab1656',
    messagingSenderId: '181662988899',
    projectId: 'wisdom-class-management',
    authDomain: 'wisdom-class-management.firebaseapp.com',
    storageBucket: 'wisdom-class-management.firebasestorage.app',
  );
}
